<script setup lang='ts'>
import { TagIcon } from 'tdesign-icons-vue-next'
</script>

<template>
  <div class="m-5">
    <t-card
      :elevation="2"
      class="flex-1/5 pt-2"
    >
      <var-cell>
        <div
          class="p-3"
        >
          <t-card
            :elevation="2"
            :radius="0"
          >
            <div class="flex items-center text-xl font-bold">
              <TagIcon />
              Tag
            </div>
          </t-card>
          <t-card
            :elevation="2"
            :radius="0"
            style="border-top: 0.025px solid #e8e8e8; border-radius: 0;"
          >
            <t-space
              direction="vertical"
              class="p-5"
            >
              <div
                class="h-55vh w-35vh flex-wrap justify-center overflow-auto"
              >
                <t-button
                  theme="success"
                >
                  贪心算法
                </t-button>
                <t-button
                  theme="success"
                >
                  冒泡排序
                </t-button>
                <t-button
                  theme="success"
                >
                  插入排序
                </t-button>
                <t-button
                  theme="success"
                >
                  线性排序算法
                </t-button>
                <t-button
                  theme="success"
                >
                  计数排序
                </t-button>
                <t-button
                  theme="success"
                >
                  外部排序 - k 路归并败者树
                </t-button>
                <t-button
                  theme="success"
                >
                  基数排序
                </t-button>
                <t-button
                  theme="success"
                >
                  外部排序 - 最佳归并树
                </t-button>
                <t-button
                  theme="success"
                >
                  合并排序
                </t-button>
                <t-button
                  theme="success"
                >
                  Strassen 矩阵乘法
                </t-button>
                <t-button
                  theme="success"
                >
                  多边形游戏
                </t-button>
                <t-button
                  theme="success"
                >
                  快速排序
                </t-button>
                <t-button
                  theme="success"
                >
                  最接近点对问题
                </t-button>
                <t-button
                  theme="success"
                >
                  圆排列问题
                </t-button>
                <t-button
                  theme="success"
                >
                  连续邮资问题
                </t-button>
                <t-button
                  theme="success"
                >
                  随机数
                </t-button>
                <t-button
                  theme="success"
                >
                  Sherwood 舍伍德算法
                </t-button>
                <t-button
                  theme="success"
                >
                  Monte Carlo 蒙特卡罗算法
                </t-button>
                <t-button
                  theme="success"
                >
                  计算定积分
                </t-button>
                <t-button
                  theme="success"
                >
                  解非线性方程组
                </t-button>
                <t-button
                  theme="success"
                >
                  线性时间选择算法
                </t-button>
                <t-button
                  theme="success"
                >
                  Boruvka 算法(最小生成树)
                </t-button>
                <t-button
                  theme="success"
                >
                  AOV / AOE 网络
                </t-button>
                <t-button
                  theme="success"
                >
                  集合覆盖问题的近似算法
                </t-button>
                <t-button
                  theme="success"
                >
                  最小费用流问题
                </t-button>
                <t-button
                  theme="success"
                >
                  稳定婚姻问题
                </t-button>
                <t-button
                  theme="success"
                >
                  最大网络流问题
                </t-button>
                <t-button
                  theme="success"
                >
                  多机调度问题
                </t-button>
                <t-button
                  theme="success"
                >
                  树型 DP
                </t-button>
                <t-button
                  theme="success"
                >
                  最优装载
                </t-button>
                <t-button
                  theme="success"
                >
                  活动安排问题
                </t-button>
                <t-button
                  theme="success"
                >
                  Johnson 算法(多源最短路径)
                </t-button>
                <t-button
                  theme="success"
                >
                  Fleury 算法(欧拉回路)
                </t-button>
                <t-button
                  theme="success"
                >
                  差分约束系统
                </t-button>
                <t-button
                  theme="success"
                >
                  中国邮递员问题
                </t-button>
                <t-button
                  theme="success"
                >
                  批处理作业调度
                </t-button>
                <t-button
                  theme="success"
                >
                  图的 m 着色问题
                </t-button>
                <t-button
                  theme="success"
                >
                  单源最短路径
                </t-button>
                <t-button
                  theme="success"
                >
                  哈夫曼编码
                </t-button>
                <t-button
                  theme="success"
                >
                  最优装载
                </t-button>
                <t-button
                  theme="success"
                >
                  电路布线
                </t-button>
                <t-button
                  theme="success"
                >
                  多边形游戏
                </t-button>
                <t-button
                  theme="success"
                >
                  图像压缩
                </t-button>
                <t-button
                  theme="success"
                >
                  电路布线
                </t-button>
              </div>
            </t-space>
          </t-card>
          <t-button
            theme="warning"
            block
            class="m-t-2"
          >
            Pick One
          </t-button>
        </div>
      </var-cell>
    </t-card>
  </div>
</template>

<style scoped>
::-webkit-scrollbar{
  display: none;
}
</style>
